Adding A Blog named as Top 4 VS Code extension every developer should use
slurpcode/slurp pull request #1137
Opened 2021-08-24 18:41 UTC by pulkitgovrani

Please review this

2021-08-24 20:10 UTC, BaseMax approved these changes
LGTM.

2021-08-24 20:12 UTC, BaseMax commented
A suggestion: It would be great if you link to add-ins page.

2021-08-24 20:49 UTC, Majalian submitted a review, later dismissed

2021-08-25 10:34 UTC, johnbampton requested changes

2021-08-25 10:34 UTC, johnbampton commented on doc/source/vs-code-extension-every-developer-should-use.md
> +
```suggestion
```

2021-08-25 10:34 UTC, johnbampton commented on doc/source/vs-code-extension-every-developer-should-use.md
> +# :boom:Top 4 VS Code extensions every developer should use
```suggestion
# :boom: Top 4 VS Code extensions every developer should use
```

2021-08-25 10:39 UTC, johnbampton requested changes
Please add your menu link in `index.rst` in the general technical area.

`doc/source/index.rst`

2021-08-25 10:46 UTC, pulkitgovrani commented
> Please add your menu link in `index.rst` in the general technical area.
> 
> `doc/source/index.rst`

I have done that, Please review it again

2021-08-25 11:09 UTC, jbampton requested changes

2021-08-25 11:09 UTC, jbampton commented on doc/source/what-programming-language.md
>  python is easier to learn.
```suggestion
Python is easier to learn.
```

2021-08-25 11:09 UTC, jbampton commented on doc/source/what-programming-language.md
>  So I am pretty sure you must have made your mind till now that learning python
```suggestion
So I am pretty sure you must have made your mind till now that learning Python
```

2021-08-25 11:11 UTC, jbampton requested changes

2021-08-25 11:11 UTC, jbampton commented on doc/source/vs-code-extension-every-developer-should-use.md
> +## 3. Javascript Code Snippets:
```suggestion
## 3. JavaScript Code Snippets:
```

2021-08-25 11:11 UTC, jbampton commented on doc/source/vs-code-extension-every-developer-should-use.md
> +As the name suggests this extension gives you many javascript code snippets thus reducing time to setup the code. It provides different types of ES6 Snippets including arrays, DOM manipulation, etc.
```suggestion
As the name suggests this extension gives you many JavaScript code snippets thus reducing time to setup the code. It provides different types of ES6 Snippets including arrays, DOM manipulation, etc.
```

2021-08-25 11:11 UTC, jbampton commented on doc/source/vs-code-extension-every-developer-should-use.md
> +This is one of the personal favourite extensions of mine. It includes simple functioning i.e, it maches starting and ending brackets in vs code which eventually helps you to resolve the errors faster
```suggestion
This is one of the personal favourite extensions of mine. It includes simple functioning i.e, it matches starting and ending brackets in vs code which eventually helps you to resolve the errors faster.
```

2021-08-25 11:16 UTC, jbampton requested changes

2021-08-25 11:16 UTC, jbampton commented on doc/source/vs-code-extension-every-developer-should-use.md
> +##  1. Live Server:
```suggestion
## 1. Live Server:
```

2021-08-29 14:29 UTC, closed without merging