Poisson-Distribution
slurpcode/slurp pull request #1310
Opened 2022-01-14 16:50 UTC by ayushrana182

Page for Poisson Distribution

2022-01-14 17:25 UTC, BaseMax commented
Maybe its good to change `μ = 4` to:
```
`μ = 4`
```

2022-01-15 02:43 UTC, ayushrana182 commented
thanks for the suggestion Max, updated it according to your suggestion. :)

2022-01-15 03:08 UTC, jbampton requested changes
Looks like you missed the menu entry in `index.rst` in the maths section

2022-01-16 08:17 UTC, jbampton approved these changes

2022-01-16 08:17 UTC, merged