adding Boris Spassky, Jungle Drum Bass files
slurpcode/slurp pull request #1366
Opened 2022-01-25 11:51 UTC by HadeerAIA

Please check this files

2022-01-25 12:22 UTC, jbampton requested changes
Please use all lowercase filenames

2022-01-25 12:30 UTC, HadeerAIA commented
> Please use all lowercase filenames
It's only the title of the pull request but the files inside all in lowercase, but I will fix it too

2022-01-25 13:12 UTC, jbampton requested changes
So the actual files themselves like the picture of Boris should be all lowercase as well

2022-01-26 10:01 UTC, jbampton requested changes
Page should be in the "Sound" section

2022-01-27 06:13 UTC, jbampton commented on doc/source/jungle_drum_bass.md
> +-	Every Noise at Once
```suggestion
- MENNYEK KAPUI - Az elektroniks zene évtizede (The decade of electronic music)
- Wikipedia
- Ishkur's Guide to Electronic Music
- Every Noise at Once 
```

2022-01-27 07:12 UTC, merged