6 files uploaded
slurpcode/slurp pull request #1444
Opened 2022-02-09 15:36 UTC by HadeerAIA

Please check these files

2022-02-11 11:52 UTC, ayushrana182 requested changes
there's a spell-check issue in on of the file, could you correct that please?

2022-02-11 12:08 UTC, HadeerAIA commented
> there's a spell-check issue in on of the file, could you correct that please?

In which file please?

2022-02-11 12:47 UTC, ayushrana182 commented
doc/source/continuous-probability-distribution.md:205:274: "binominal" is a misspelling of "binomial"

2022-02-11 13:24 UTC, HadeerAIA commented
> doc/source/continuous-probability-distribution.md:205:274: "binominal" is a misspelling of "binomial"

It's not in the 6 files included in this pull request 
the files that uploaded was "Staccatone , Optophonic_Piano, Synthetic_Tone, Theremin, Electrophon, Hugoniot_Organ"  
"continuous-probability-distribution.md" Not one of them

2022-02-11 13:29 UTC, HadeerAIA commented
> It's just a few second's change, I requested because you are the only one pushing changes now

Oh ok, I was thinking just about the 6 files right now, But ok I will check the spelling and push it again.

2022-02-14 05:24 UTC, HadeerAIA commented on doc/source/hugoniot_organ.md
> +![hugoniot_organ](_static/images/hugoniot_organ/hugoniot_organ.png)
Done

2022-02-14 05:28 UTC, HadeerAIA commented on doc/source/hugoniot_organ.md
> +Next topic: Theremin
I have reordered the files according to the next topic mentioned in the PDF files sent, you could review it again and tell me if there is anything left.

2022-02-15 04:08 UTC, merged