parallel universe
slurpcode/slurp pull request #1642
Opened 2022-04-23 06:02 UTC by smriad

2022-04-23 06:09 UTC, ayushrana182 reviewed
Shouldn't check markdown links pass the tests? Maybe check the links?

2022-04-23 07:15 UTC, jbampton reviewed
I am looking into the Check markdown links problem.

Might be that it's looking for `master` branch and we renamed it to `main`

2022-04-23 07:17 UTC, jbampton commented
<img width="1015" alt="Screen Shot 2022-04-23 at 5 17 19 pm" src="https://user-images.githubusercontent.com/418747/164884517-d5cec23f-6408-4d06-8acb-349c7c853ea1.png">

2022-04-23 07:19 UTC, jbampton commented
https://github.com/gaurav-nelson/github-action-markdown-link-check

<img width="1071" alt="Screen Shot 2022-04-23 at 5 19 19 pm" src="https://user-images.githubusercontent.com/418747/164884600-17271dc6-73b2-4b32-96d8-a4507fa190c9.png">

2022-05-14 01:16 UTC, jbampton requested changes
This needs to be removed completely not just commented out

2022-05-14 08:13 UTC, smriad commented
> This needs to be removed completely not just commented out

Okay

2022-05-14 11:17 UTC, smriad commented
> This needs to be removed completely not just commented out

@jbampton Please check now

2022-06-04 02:59 UTC, jbampton requested changes
File permissions are wrong.  Also `pages/parallel.html` should be removed.

2022-06-04 03:00 UTC, jbampton commented on docs/_config.yml
> +  - pages/parallel.html
```suggestion
```

2022-06-13 06:53 UTC, jbampton approved these changes

2022-06-13 06:53 UTC, merged