Add Warsaw doc
slurpcode/slurp pull request #1908
Opened 2022-10-06 03:16 UTC by Kevan-Y

Fixes #1878 

## Description
- Add Warsaw doc

2022-10-06 03:38 UTC, jbampton requested changes
Please use `-` in filenames

2022-10-06 03:43 UTC, Kevan-Y commented
> Please use `-` in filenames

Oupsy right, I got used to use `_`

2022-10-06 04:12 UTC, jbampton commented on doc/source/warsaw.md
> +In the heart of the city is located in the beautiful Old Town square where tourists and locals converge, in the surroundings you can see its cobbled streets with houses of medieval architecture and t
```suggestion

In the heart of the city is located in the beautiful Old Town square where tourists and locals converge, in the surroundings you can see its cobbled streets with houses of medieval architecture and their colorful facades. You can have a drink in the restaurants with terraces that surround the square and see the street artists or painters that are usually in this area.
```

2022-10-06 04:12 UTC, jbampton commented on doc/source/warsaw.md
> +The recommendation is to observe the most beautiful buildings that are on the banks of the Vistula River and then visit the most important churches such as San Jacek, the Holy Spirit and the Visitati
```suggestion

The recommendation is to observe the most beautiful buildings that are on the banks of the Vistula River and then visit the most important churches such as San Jacek, the Holy Spirit and the Visitation of the Virgin Mary.
```

2022-10-06 04:25 UTC, jbampton reviewed
Do you shrink the images ?

https://slurp--1908.org.readthedocs.build/en/1908/zurich.html

2022-10-06 21:28 UTC, Kevan-Y commented
> Do you shrink the images ?
> 
> https://slurp--1908.org.readthedocs.build/en/1908/zurich.html

Nope, I saved it as it is. Did not touch the size of the image

2022-10-07 15:03 UTC, jbampton commented
When I save the images they are larger.

Looks like your pr is different

2022-10-07 20:30 UTC, Kevan-Y commented
@jbampton, Does my old build get replace by new one after a new commit?

If so, I can't seems to get the correct size. I'm not sure if it's OS issue or something else.

Steps of my file saving:
1. Open docx file
2. Click on the image
3. Save as Picture 
4. Rename and put in the correct folder

2022-10-07 20:51 UTC, jbampton commented
Yes as long as you commit the work it does update.

But I grab the images from the docs differently.

I open the doc in `LibreOffice` and then click on an image and select copy.

Then I open `preview` image editor and select `new from clipboard`

Free and open source:  https://www.libreoffice.org/

2022-10-07 21:30 UTC, Kevan-Y commented
Updated with the correct size of image. I do not know why microsoft office produce an incorrect image size. Good to know LibreOffice works. Thanks

2022-10-08 13:15 UTC, jbampton approved these changes

2022-10-08 13:25 UTC, merged