Add codespell to the pre commit config #2109
slurpcode/slurp pull request #2112
Opened 2023-03-26 16:58 UTC by anufdo

Add codespell to the pre commit

2023-03-26 17:04 UTC, jbampton requested changes
Will need to fix the spelling in the `doc` folder not `docs`.

See https://github.com/slurpcode/slurp/pull/2111/files

2023-03-26 17:04 UTC, jbampton commented on .codespellrc
> +  - docs/*
```suggestion
  - doc/*
```

2023-03-26 17:14 UTC, anufdo commented on .codespellrc
> +  - docs/*
Yes.

2023-03-26 17:15 UTC, jbampton commented
https://github.com/One-Language/One/blob/main/CONTRIBUTING.md#pre-commit

2023-03-26 17:35 UTC, anufdo commented on .codespellrc
> +  - docs/*
https://github.com/slurpcode/slurp/pull/2112/commits/8ad8ad05bdef64214b141e87142b3752ba598d24

2023-03-27 18:09 UTC, jbampton commented
https://github.com/slurpcode/slurp/actions/runs/4533746250/jobs/7986975862?pr=2112

2023-03-28 04:21 UTC, anufdo commented
Now it is scanning doc folder.
Is it now Ok to set codespell to fix spilling errors automatically?
It will change lot of files automatically.

2023-03-28 21:10 UTC, jbampton commented
You can use:

`slurp % codespell doc/source | cut -f2 -d' ' | tr A-Z a-z | sort | uniq`

as a starting point for the ignore list.

2023-03-29 16:24 UTC, jbampton commented on .pre-commit-config.yaml
> +minimum_pre_commit_version: "1.20.0"
```suggestion
minimum_pre_commit_version: '1.20.0'
```

2023-06-11 05:02 UTC, jbampton approved these changes

2023-06-11 05:03 UTC, merged