Pr/2102
slurpcode/slurp pull request #2116
Opened 2023-03-27 23:45 UTC by wickedknock

- updated super linter for python and golang
- added lint.js to test linters locally

2023-03-27 23:48 UTC, jbampton requested changes
Please remove `lint.js` as we use pre-commit locally on git commit

2023-03-27 23:51 UTC, jbampton commented on .gitignore
> +.env
```suggestion
.env

```

2023-03-27 23:51 UTC, jbampton commented on .eslintrc.json
> +
```suggestion
 
```

2023-03-27 23:57 UTC, jbampton reviewed
Keep lint.js change my mind !!

2023-03-28 08:09 UTC, BaseMax commented
Thanks.

2023-03-30 12:55 UTC, wickedknock commented
@jbampton  Its only failing on dead links now , should I start working on other issues?

2023-03-30 18:53 UTC, jbampton commented
https://app.codacy.com/gh/slurpcode/slurp/pullRequest?prid=11440795

2023-03-31 13:05 UTC, jbampton requested changes
https://deepsource.io/gh/slurpcode/slurp/run/99c356b4-0ac6-4341-accb-31462fc94470/javascript/

2023-04-04 10:37 UTC, jbampton approved these changes

2023-04-04 10:39 UTC, merged