Add another doc: Exponential Distribution
slurpcode/slurp pull request #2142
Opened 2023-03-31 12:03 UTC by janus

Fix https://github.com/slurpcode/slurp/issues/2126

2023-03-31 12:44 UTC, jbampton requested changes

2023-03-31 12:44 UTC, jbampton commented on doc/source/exponential-distribution.md
> +# Exponential Distribution
https://emojipedia.org/

Missing title emoji :)

2023-03-31 12:45 UTC, jbampton commented
https://slurp--2142.org.readthedocs.build/en/2142/exponential-distribution.html

<img width="255" alt="Screen Shot 2023-03-31 at 10 41 58 pm" src="https://user-images.githubusercontent.com/418747/229123483-b8adfb94-ba84-4ec5-86f4-efdc4fb1ae93.png">

2023-03-31 19:59 UTC, janus commented on doc/source/exponential-distribution.md
> +# Exponential Distribution
I have added emoji, mutiply X.

2023-04-02 04:13 UTC, jbampton approved these changes

2023-04-02 04:13 UTC, merged