Seek rb fix for windows #2141 fix
slurpcode/slurp pull request #2176
Opened 2023-04-05 15:24 UTC by anufdo

2023-04-06 16:40 UTC, jbampton commented on seek/seek.rb
>      `open "jobs/#{filename}.csv"`
Needs to use `exec` here too

2023-04-07 02:02 UTC, anufdo commented on seek/seek.rb
>      `open "jobs/#{filename}.csv"`
Ok.

2023-04-08 17:18 UTC, wickedknock reviewed
add error handling if the file is not found in parse method.

2023-04-08 17:20 UTC, BaseMax commented
Hi Saad, Welcome. @wickedknock

2023-04-08 17:21 UTC, wickedknock commented
> Hi Saad, Welcome. @wickedknock

A gun was put to my head sorry XD

2023-04-08 17:33 UTC, BaseMax commented
> A gun was put to my head sorry XD

How do you mean?

2023-04-08 17:34 UTC, jbampton commented on seek/seek.rb
> +    exec(%(xdg-open  "jobs/#{filename}.csv"))
```suggestion
    exec(%(xdg-open "jobs/#{filename}.csv"))
```

2023-04-08 17:36 UTC, anufdo commented on seek/seek.rb
> +    exec(%(xdg-open  "jobs/#{filename}.csv"))
OK. done

2023-04-08 17:58 UTC, jbampton commented on seek/seek.rb
> +  is_windows = (RbConfig::CONFIG["host_os"] =~ /mswin|mingw|cygwin/)
```suggestion
  is_windows = (RbConfig::CONFIG["host_os"] =~ /cygwin|mingw|mswin/)
```

2023-04-08 18:05 UTC, anufdo commented on seek/seek.rb
> +  is_windows = (RbConfig::CONFIG["host_os"] =~ /mswin|mingw|cygwin/)
Done

2023-04-08 18:08 UTC, BaseMax reviewed
John is really great to review the code. You must learn as must as you can from him. It's +20 years of experience.

2023-04-08 19:23 UTC, jbampton requested changes
It would be better to use `===` instead of `=~` since `===` returns a boolean.

Also it seems that we don't need the extra `()` around `is_mac` for example or say `is_windows` etc.  Please test with Rubocop.

```
irb(main):011:0> RbConfig::CONFIG["host_os"] =~ /linux/
=> nil
irb(main):012:0> RbConfig::CONFIG["host_os"] =~ /darwin21/
=> 0
irb(main):013:0> /linux/ === RbConfig::CONFIG["host_os"]
=> false
irb(main):014:0> /darwin21/ === RbConfig::CONFIG["host_os"]
=> true
irb(main):015:0> is_mac = /darwin21/ === RbConfig::CONFIG["host_os"]
=> true
irb(main):016:0> is_mac
=> true
irb(main):017:0> /linux/ =~ RbConfig::CONFIG["host_os"]
=> nil
irb(main):018:0> /darwin21/ =~ RbConfig::CONFIG["host_os"]
=> 0
irb(main):019:0> 
```

`=~` returns the position of the match so `0` is a match at first position for say `d` in `darwin21`

Examples of `===` and `=~` here:

https://docs.ruby-lang.org/en/3.0/Regexp.html#method-i-3D-3D-3D

Note it also should be

`rxp === str → true or false` or

`rxp =~ str → integer or nil`

https://github.com/ruby/irb

2023-04-10 13:42 UTC, anufdo commented
![image](https://user-images.githubusercontent.com/8244245/230912680-98900276-f369-4217-a9fe-21adb4580962.png)

2023-04-10 13:44 UTC, anufdo commented
It should be modified like this.
```
# determine the current operating system
host_os = RbConfig::CONFIG["host_os"]

case host_os
when /cygwin|mingw|mswin/
  exec(%(start "" "jobs/#{filename}.csv"))
when /linux/
  exec(%(xdg-open "jobs/#{filename}.csv"))
when /darwin/
  exec(%(open "jobs/#{filename}.csv"))
end
```

2023-04-10 14:13 UTC, jbampton reviewed
https://app.codacy.com/gh/slurpcode/slurp/pullRequest?prid=11506388

2023-04-10 14:51 UTC, jbampton commented on seek/seek.rb
> +  # determine the current operating system
```suggestion
```

2023-04-10 15:04 UTC, jbampton approved these changes

2023-04-10 15:05 UTC, merged