👮🏽 Rubocop config 👮🏽 #484
slurpcode/slurp pull request #595
Opened 2020-09-22 07:53 UTC by tHe-AK

- Added missing rubocop configs & disabled few rules.
- Fixed 'Style/StringConcatenation' rule errors

2020-09-22 13:29 UTC, jbampton commented
Looks like the build failed here -> https://app.circleci.com/pipelines/github/slurpcode/slurp/1363/workflows/a6be8cb7-3315-48b9-b943-ad87ac2fb499/jobs/5201  you will need to fix that.

2020-09-22 13:34 UTC, jbampton requested changes

2020-09-22 13:34 UTC, jbampton commented on .rubocop.yml
> +  Enabled: true
```suggestion
  Enabled: true

```

2020-09-22 14:44 UTC, tHe-AK commented on .rubocop.yml
> +  Enabled: true
https://app.circleci.com/pipelines/github/slurpcode/slurp/1364/workflows/6c16fe9b-bb59-463a-9b17-f0fc1874b71c

2020-09-25 13:49 UTC, jbampton commented
Needs a rebase

2020-09-26 02:34 UTC, closed without merging

2020-09-27 11:04 UTC, jbampton commented
Why did you close this ?

2020-09-28 02:09 UTC, tHe-AK commented
I have deleted the source branch and created a new branch with same name to have a clean git history. I was not aware that deleting source will close the PR, as this is not the behaviour in BitBucket.

2020-09-28 14:49 UTC, jbampton commented
If you had rebased like I said you would have a clean git history.  Or you can squash your commits.