feat: added favicon
slurpcode/slurp pull request #716
Opened 2020-12-06 00:21 UTC by TJSteel

2020-12-06 03:07 UTC, jbampton requested changes

2020-12-06 03:07 UTC, jbampton commented on logorama/_includes/head.html
> +  <link rel="icon" type="image/gif" href="/assets/images/LogoRama_favicon.ico">
Can we just call it -> favicon.ico -> all lowercase ?

2020-12-06 03:08 UTC, jbampton commented
Needs a rebase too

2021-01-10 20:45 UTC, jbampton commented
Hey @TJSteel can you rebase again ?

I want to merge this PR next.

2021-01-12 19:49 UTC, TJSteel commented
> Hey @TJSteel can you rebase again ?
> 
> I want to merge this PR next.

just done this now, would a rebase and merge not have done the same thing though?

2021-01-18 15:19 UTC, merged